name: my_authentication
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  jwt_decode: ^0.3.1
  my_cache:
    path: ../cache
  my_http_client:
    path: ../http_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0
