name: my_http_client
description: Dart package which implement http client.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  connectivity_plus: ^1.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  very_good_analysis: ^2.3.0
